require "./augment/exception"
require "./augment/builder"
require "./augment/parser"
require "./augment/command"
require "./augment/root_command"

# Dynamically generated by `Builder`
require "./augment/run"
